### ISSUE TITLE
Unable to setup vhive with gvisor

### ISSUE THREAD

**Issue by alexandrinapanfil** [vhive-serverless/vHive#635]
**Describe the bug**
Trying to set up a single node vhive cluster with gvisor, however I keep getting an error log that the vhive cri sock is being already in use.
**To Reproduce**
on Cloudlab with [vhive-ubuntu20] profile, running a xl170 node;

`git clone https://github.com/vhive-serverless/vHive.git`
`cd vhive`
`./scripts/cloudlab/setup_node.sh gvisor` 
`sudo screen containerd; sleep 5;`

in another terminal:
`sudo PATH=$PATH screen /usr/local/bin/gvisor-containerd --config /etc/gvisor-containerd/config.toml`

in another terminal:
`source /etc/profile && go build;`
`sudo ./vhive --sandbox gvisor`

**Expected behavior**
successfully start ./vhive
**Logs**
`FATA[0000] failed to setup GVisorCRI: failed to listen: listen unix /etc/vhive-cri/vhive-cri.sock: bind: address already in use`

**Comment by ustiugov** [comment]
hi @alexandrinapanfil, is the machine clean, i.e., is it the first run of vhive? this error means that there is already a daemon that listens to this socket. please check and kill all `vhive` processes and delete this file before re-instantiating the cluster. If this doesn't help, start with a clean machine again.

**Comment by jingren1021** [comment]
I got error as below while executing the same commands on a clean ubuntu server.

```
FATA[0010] failed to setup GVisorCRI: failed to create firecracker service failed to create gvisor-coordinator: failed to start containerd client: failed to dial "/run/gvisor-containerd/gvisor-containerd.sock": context deadline exceeded
```

Any idea on how to fix this?

**Comment by ustiugov** [comment]
@jingren1021 we have an update in the maintainer list so I am taking over. could you please supply a complete set of logs from containerd, vhive, etc?

**Comment by CuriousGeorgiy** [comment]
I tried running `scripts/cloudlab/start_onenode_vhive_cluser.sh gvisor` and everything works. Seems like you forgot to pass the `-address  /run/gvisor-containerd/gvisor-containerd.sock` option to `/usr/local/bin/gvisor-containerd`:
> in another terminal:
`sudo PATH=$PATH screen /usr/local/bin/gvisor-containerd --config /etc/gvisor-containerd/config.toml`

https://github.com/vhive-serverless/vHive/blob/cc70f39715d76c49ede5e9325e5c7b364478f11e/scripts/cloudlab/start_onenode_vhive_cluster.sh#L52
