### ISSUE TITLE
Functions struck in deploying state

### ISSUE THREAD

**Issue by catchabhisek** [vhive-serverless/vHive#649]
**Describe the bug**
While deploying the vhive as per the documentation. I have experienced the following error:
WARN[0000] Failed to deploy function helloworld-0, configs/knative_workloads/helloworld.yaml: exit status 1
Error: Internal error occurred: failed calling webhook "webhook.serving.knative.dev": failed to call webhook: Post "https://webhook.knative-serving.svc:443/?timeout=10s": Not Found

I have deleted the webhooks for solving the problem. The workload is struck in deploying state while the pods are running.
```
root@awsum:/home/abhisek/SnapStore/vhive# kubectl get deployment
NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
helloworld-0-00001-deployment   1/1     1            1           5m31s
root@awsum:/home/abhisek/SnapStore/vhive# kubectl get revision
NAME                 CONFIG NAME    K8S SERVICE NAME   GENERATION   READY     REASON      ACTUAL REPLICAS   DESIRED REPLICAS
helloworld-0-00001   helloworld-0                      1            Unknown   Deploying                     
root@awsum:/home/abhisek/SnapStore/vhive# kn service list
NAME           URL                                                  LATEST   AGE     CONDITIONS   READY     REASON
helloworld-0   http://helloworld-0.default.192.168.1.240.sslip.io            5m38s   0 OK / 3     Unknown   RevisionMissing : Configuration "helloworld-0" is waiting for a Revision to become ready.
```

**To Reproduce**
1. Deploy vhive on a single node.
2. Delete the webhooks, in case it is not found.
3. Deploy a function.

**Expected behavior**
The services would have been deployed, if the pod is running

**Comment by niravnshah** [comment]
Hi @catchabhisek , not sure if you are running the single node cluster on a system, which is behind a proxy. If so, try adding “.knative-serving.svc” to the no_proxy settings. This had helped me.

All the no proxy settings i add for various reasons not all of these might be necessary, however i have kept them just to not run into proxy related issues...
```
sudo echo 'no_proxy="<ip address of current system>,localhost,127.0.0.1/8,192.168.49.2,192.168.0.0/16,192.168.0.1/16,10.96.0.0/16,10.165.160.4,/run/containerd/containerd.sock,/etc/vhive-cri/vhive-cri.sock,.knative-serving.svc,.sslip.io,::1"' >> /etc/environment
```

**Comment by ustiugov** [comment]
thank you @niravnshah 

@catchabhisek did you find a solution? please re-open if this is still relevant
