### ISSUE TITLE
Cannot deploy functions from worker node

### ISSUE THREAD

**Issue by denllx** [vhive-serverless/vHive#681]
**Describe the bug**
I followed the [quickstart guide](https://github.com/vhive-serverless/vHive/blob/main/docs/quickstart_guide.md) to set up a 2-node vHive cluster. However, I discovered that in the step V, if I want to deploy a function on a worker node and execute the command:
`kn service apply stargz-test -f configs/knative_workloads/stargz-node.yaml --concurrency-target 1
`
, it wil raise these errrors:
`Error: services.serving.knative.dev is forbidden: User "system:node:node-1.vhive-test.faas-sched-pg0.utah.cloudlab.us" cannot list resource "services" in API group "serving.knative.dev" in the namespace "default"`.

Is it designed that only master node could deploy functions, or something went wrong here?

**Comment by ustiugov** [comment]
@denllx please kindly supply all the relevant log snippets and full logs, steps to reproduce, etc.

**Comment by leokondrashov** [comment]
This is the intended behaviour.
