### ISSUE TITLE
Disable local registry tests from CRI tests

### ISSUE THREAD

**Issue by anshalshukla** [vhive-serverless/vHive#703]
Current vHive CloudLab profile uses Ubuntu 20.04 image, which does not have
the skopeo package which is needed to pull image for local registry tests — temporarily disable these tests until #709 is resolved.

**Comment by CuriousGeorgiy** [comment]
> skopeo package isn't available in Ubuntu 20+

Skopeo package is available starting from Ubuntu 20.10[^1].

AFAIC, we need to update the vHive profile on CloudLab to use Ubuntu 20.10 if we want to run tests manually or if we want base CI runner images on it.

[^1]: https://github.com/containers/skopeo/blob/main/install.md#ubuntu

**Comment by ustiugov** [comment]
@CuriousGeorgiy it would be unreasonable to support an unstable version of Ubuntu. We can upgrade to Ubuntu 22 after we finish the ongoing upgrades.
