### ISSUE TITLE
Cloudlab profile not changing volume erratically

### ISSUE THREAD

**Issue by JooyoungPark73** [vhive-serverless/vHive#711]
**Describe the bug**
Cloudlab vhive-ubuntu20 profile **_sometimes_** does not expand root fs size to max, keeping it at 16GB.

**To Reproduce**
Instantiate a cluster on cloudlab, and reload images until you find out your root partition is only 16GB when you df -h

**Expected behavior**
root partition is expected to be around 440GB

**Logs**
before reload: 
```nehalem@node-1:~$ df  -h
Filesystem                                Size  Used Avail Use% Mounted on
udev                                       32G     0   32G   0% /dev
tmpfs                                     6.3G  3.2M  6.3G   1% /run
/dev/sda1                               **440G**  7.3G  415G   2% /
tmpfs                                      32G     0   32G   0% /dev/shm
tmpfs                                     5.0M     0  5.0M   0% /run/lock
tmpfs                                      32G     0   32G   0% /sys/fs/cgroup
ops.utah.cloudlab.us:/proj/ntu-cloud-PG0  100G  5.6G   95G   6% /proj/ntu-cloud-PG0
ops.utah.cloudlab.us:/share                20T   15G   20T   1% /share
tmpfs                                     6.3G     0  6.3G   0% /run/user/20001
```

after reload:
```
nehalem@node-1:~$ df -h
Filesystem                                Size  Used Avail Use% Mounted on
udev                                       32G     0   32G   0% /dev
tmpfs                                     6.3G  1.2M  6.3G   1% /run
/dev/sda1                                **16G**  2.5G   13G  17% /
tmpfs                                      32G     0   32G   0% /dev/shm
tmpfs                                     5.0M     0  5.0M   0% /run/lock
tmpfs                                      32G     0   32G   0% /sys/fs/cgroup
ops.utah.cloudlab.us:/proj/ntu-cloud-PG0  100G  5.6G   95G   6% /proj/ntu-cloud-PG0
ops.utah.cloudlab.us:/share                20T   15G   20T   1% /share
tmpfs                                     6.3G     0  6.3G   0% /run/user/20001
```
**Notes**
Currently, we support only Ubuntu 18 (x86) bare-metal hosts, however
we encourage the users to reports Issues that appear in different settings.
We will try to help and potentially include these scenarios into our CI
if given enough interest from the community.

**Comment by NeHalem90** [comment]
reported the issue to cloudlab
[link](https://groups.google.com/g/cloudlab-users/c/I2QA-aUc3jI)

**Comment by ustiugov** [comment]
@JooyoungPark73 what is the status of this?

**Comment by JooyoungPark73** [comment]
@ustiugov They did not respond to my report. Shouldn I resubmit it?

**Comment by ustiugov** [comment]
can you check if there is a support email/contact form? @JooyoungPark73

**Comment by JooyoungPark73** [comment]
@ustiugov They have [Google Groups](https://groups.google.com/g/cloudlab-users)

**Comment by ustiugov** [comment]
@JooyoungPark73 is the problem still relevant?

**Comment by JooyoungPark73** [comment]
yes. This is Cloudlab side problem. I don't think they run boot script when reloading.
