### ISSUE TITLE
Flannel network deployment issue

### ISSUE THREAD

**Issue by cvetkovic** [vhive-serverless/vHive#725]
Setting up CNI fails on big clusters that have their Ethernet interface names different from the ones on the master node. Symptoms include `canal` pods not being ready in K8s CLI output.

The problem is caused by `export IFACE` command in `setup_master_node.sh`. The DaemonSet interface uses this env. var.

EDIT:
To be resolved by #594.

**Comment by ustiugov** [comment]
@cvetkovic does the problem still stand?

**Comment by cvetkovic** [comment]
Solved by this [commit](https://github.com/vhive-serverless/vHive/commit/397e36c08a5b2d7b6609b1ad0a7ec06eaa805bc8), but just on `hy` branch.

**Comment by ustiugov** [comment]
ok, let's keep it open until #594 is merged.
