### ISSUE TITLE
Unable to locate package kubeadm

### ISSUE THREAD

**Issue by pzg250** [vhive-serverless/vHive#742]
**Describe the bug**
use 2 aws ec2 instances, ubuntu 20.04 to deploy the vHive. 
meeting an error at node setup script. 
Please tell me if more info is needed.

Appreciate any advice.

**To Reproduce**
```
git clone --depth=1 https://github.com/vhive-serverless/vhive.git
cd vhive
mkdir -p /tmp/vhive-logs
./scripts/cloudlab/setup_node.sh stock-only use-stargz > >(tee -a /tmp/vhive-logs/setup_node.stdout) 2> >(tee -a /tmp/vhive-logs/setup_node.stderr >&2)
```
Output:
```
APT::Periodic::Update-Package-Lists "0";
APT::Periodic::Download-Upgradeable-Packages "0";
APT::Periodic::AutocleanInterval "0";
APT::Periodic::Unattended-Upgrade "0";
Created symlink /etc/systemd/system/apt-daily.service → /dev/null.
Created symlink /etc/systemd/system/apt-daily-upgrade.service → /dev/null.
sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument
containerd github.com/containerd/containerd v1.6.2 de8046a5501db9e0e478e1c10cbcfb21af4c6b2d
deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
W: GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
E: The repository 'https://apt.kubernetes.io kubernetes-xenial InRelease' is not signed.
E: Unable to locate package cri-tools
E: Unable to locate package kubeadm
E: Unable to locate package kubectl
E: Unable to locate package kubelet
E: Unable to locate package kubernetes-cni
🚧 Compile
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument
containerd-stargz-grpc
ctr-remote
--2023-05-29 12:00:31--  https://raw.githubusercontent.com/containerd/stargz-snapshotter/main/script/config/etc/systemd/system/stargz-snapshotter.service
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 312 [text/plain]
Saving to: ‘/etc/systemd/system/stargz-snapshotter.service’

     0K                                                       100% 21.0M=0s

2023-05-29 12:00:31 (21.0 MB/s) - ‘/etc/systemd/system/stargz-snapshotter.service’ saved [312/312]

Created symlink /etc/systemd/system/multi-user.target.wants/stargz-snapshotter.service → /etc/systemd/system/stargz-snapshotter.service.
```

**Expected behavior**

**Logs**
Please add relevant excerpts from the following logs: `vhive`, `firecracker-containerd`,
and if used with Kubernetes additionally `containerd` and/or other relevant
logs of Kubernetes containers and setup scripts.

**Notes**
Currently, we support only Ubuntu 18 (x86) bare-metal hosts, however
we encourage the users to reports Issues that appear in different settings.
We will try to help and potentially include these scenarios into our CI
if given enough interest from the community.

**Comment by ustiugov** [comment]
@JooyoungPark73 you had a problem with the keys before. could you please take a look? I thought we've fixed all of those already...

**Comment by JooyoungPark73** [comment]
Hi @pzg250 

https://github.com/vhive-serverless/vHive/blob/main/scripts/install_stock.sh#L50
can you change line 50 of install_stock.sh
```sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg```

to 
```sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://dl.k8s.io/apt/doc/apt-key.gpg```

and rerun and check if the error persists?
The key accessibility is kind of erratic from time to time, and changing URL may be required sometimes.

Please let me know if the problem persists.

**Comment by pzg250** [comment]
Hi @JooyoungPark73 , thank you very much. It works! 
After install the vhive I met another issuer, will open a new ticket for that.
Thanks again!
