### ISSUE TITLE
Resizing Container Resources Without Restarting Containers

### ISSUE THREAD

**Issue by Lightxyz** [vhive-serverless/vHive#803]
**Is your feature request related to a problem? Please describe.**
Cannot change CPU requests / limits for pods / containers which are running, without restarting them.

**Describe the solution you'd like**
An upgrade to Kubernetes version 1.27 would allow us to resize CPU and memory resources assigned to containers without needing to restart them. See the following:
https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md#changelog-since-v1260
"PodSpec.Container.Resources became mutable for CPU and memory resource types."

**Describe alternatives you've considered**
Editing the cpu.shares and the cpu.cfs_quota_us files enables us to adjust the CPU request and the CPU limit while the container is running, but this may interfere with the Kubernetes scheduler.
EDIT:
The [kn service update](https://github.com/knative/client/blob/main/docs/cmd/kn_service_update.md) command can adjust CPU requests / limit and memory requests of pods, but it's unclear whether it will adjust the CPU share that existing pods which are currently processing invocations get.

**Comment by ustiugov** [comment]
@Lightxyz I don't mind as it seems that Knative folks are moving to 1.25 version since knative 1.11 (we have 1.9) as the minimum required (we have 1.25 now) so it would be good to move forward. 

@Lightxyz can you take the lead on this upgrade?

**Comment by Lightxyz** [comment]
> @Lightxyz I don't mind as it seems that Knative folks are moving to 1.25 version since knative 1.11 (we have 1.9) as the minimum required (we have 1.25 now) so it would be good to move forward.
> 
> @Lightxyz can you take the lead on this upgrade?

Great, what's the status on migrating the changes from the hy branch into main?
I could then work on upgrading Kubernetes and Knative in the main branch.

**Comment by ustiugov** [comment]
you can focus on the main branch, it's already ahead of `hy`. the plan is that a new visiting student of ours will take it over in the beginning of October

**Comment by Lightxyz** [comment]
> you can focus on the `main` branch without any delay, it's already ahead of `hy`. the plan is that a new visiting student of ours will take the `hy` migration over in the beginning of October

Sounds good, thank you!

**Comment by leokondrashov** [comment]
@Lightxyz We already updated invitro and vhive to use k8s 1.29. If that is not enough, please reopen.
