### ISSUE TITLE
Enable gofmt in golangci-lint action

### ISSUE THREAD

**Issue by CuriousGeorgiy** [vhive-serverless/vHive#819]
**Describe the enhancement**
The golangci-lint tools has a very limited number of linters enabled by default. The tool can be configured via a [`.golangci.yml`](https://golangci-lint.run/usage/configuration/) file in the root of the repository[^1].

Enable the [gofmt](https://golangci-lint.run/usage/linters/#gofmt) linter at least, and, possibly, other linters.

[^1]: https://github.com/golangci/golangci-lint-action/blob/5f5f252fe2752527f5bcc957af7e8ae9591a33fa/README.md?plain=1#L57-L61

**Comment by leokondrashov** [comment]
Do we actually have lint for the code? I see only CodeQL, among linter there are only commit, links and spell checks.
