### ISSUE TITLE
github runners scripts cannot setup cri-tests environment

### ISSUE THREAD

**Issue by lrq619** [vhive-serverless/vHive#836]
**Describe the bug**
github runners scripts [setup_cri_test_env.sh](https://github.com/vhive-serverless/vHive/blob/58ddb7712f2b23bb10ae37a74af4c63b686bb151/scripts/github_runner/setup_cri_test_env.sh#L48) cannot apply helloworld.yaml.
It will give out the following errors:
```
Creating service 'helloworld' in namespace 'default':

  0.049s The Route is still working to reflect the latest desired specification.
  0.077s ...
  0.086s Configuration "helloworld" is waiting for a Revision to become ready.
Error: timeout: service 'helloworld' not ready after 600 seconds
```
I've ssh to runners and look at the pods status by `kubectl describe pods helloworld` and found out that an image `ghcr.io/vhive-serverless/queue` is giving out error: `Readiness probe failed`
 Here is the event log:
```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  30s               default-scheduler  Successfully assigned default/helloworld-00001-deployment-5d767c9c97-4kmsd to runner-3
  Normal   Pulled     29s               kubelet            Container image "index.docker.io/crccheck/hello-world@sha256:0404ca69b522f8629d7d4e9034a7afe0300b713354e8bf12ec9657581cf59400" already present on machine
  Normal   Created    26s               kubelet            Created container user-container
  Normal   Started    26s               kubelet            Started container user-container
  Normal   Pulled     26s               kubelet            Container image "ghcr.io/vhive-serverless/queue-39be6f1d08a095bd076a71d288d295b6@sha256:41259c52c99af616fae4e7a44e40c0e90eb8f5593378a4f3de5dbf35ab1df49c" already present on machine
  Normal   Created    26s               kubelet            Created container queue-proxy
  Normal   Started    26s               kubelet            Started container queue-proxy
  Warning  Unhealthy  9s (x5 over 24s)  kubelet            Readiness probe failed: Get "http://192.168.206.38:8013/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**To Reproduce**
1. Follow the steps of [.github/workflows/cri_tests.yml](https://github.com/vhive-serverless/vHive/blob/58ddb7712f2b23bb10ae37a74af4c63b686bb151/.github/workflows/cri_tests.yml#L40) until it executes setup_cri_test_env.sh
2. Follow the steps of [vHive/scripts/github_runner/setup_cri_test_env.sh](https://github.com/vhive-serverless/vHive/blob/58ddb7712f2b23bb10ae37a74af4c63b686bb151/scripts/github_runner/setup_cri_test_env.sh#L48) until `sudo KUBECONFIG=/etc/kubernetes/admin.conf kn service apply helloworld -f $VHIVE_ROOT/configs/knative_workloads/helloworld.yaml`
3. execute:
```
sudo KUBECONFIG=/etc/kubernetes/admin.conf kn service apply helloworld -f $VHIVE_ROOT/configs/knative_workloads/helloworld.yaml
```
4. check the pods status using `kubectl describe pod helloworld`

**Expected behavior**
container for `ghcr.io/vhive-serverless/queue` should also be in the status of `Ready` and do not give out error

**Logs**

**Notes**

**Comment by leokondrashov** [comment]
Can you reproduce this error with stock version of queueproxy? The switch should be possible to do even on the live system with patch to `queue-sidecar-image` in configmap `config-deployment` to change the image from `"ghcr.io/vhive-serverless/queue-39be6f1d08a095bd076a71d288d295b6@sha256:41259c52c99af616fae4e7a44e40c0e90eb8f5593378a4f3de5dbf35ab1df49c"` to the one in default config (that is downloaded from knative's repo).

**Comment by lrq619** [comment]
Updates: 
Surpurisingly, the firecracker cri tests can succeed on the `main` branch, so if trigger setup_scri_test_env.sh firecracker on the runner, it will succeed
I'm sure the problem is only related to gvisor setup

**Comment by lrq619** [comment]
I have found the cause of this bug:
In short, the bug is caused by bumping the gvisor version to 20230911.0 in this commit: https://github.com/vhive-serverless/vHive/commit/4512efdc3c9b62b11ada8e77feaf10fd6cda603c

I've now reverted the runner's gvisor version to previous ones, it can work as normal.

**Comment by lrq619** [comment]
Solved by downgrading gVisor version:
https://github.com/vhive-serverless/vHive/pull/840
