### ISSUE TITLE
Runners deployment scripts waiting for testing

### ISSUE THREAD

**Issue by lrq619** [vhive-serverless/vHive#913]
**Describe the bug**
No testing have been done since the runner scripts was updated in this commit https://github.com/vhive-serverless/vHive/commit/612788a3ca013b6abdd3f2038092ea2509ba1876

**To Reproduce**
There could be potential bugs on the runners when using this specific version of deployment script to deploy the runners

**Expected behavior**
Test whether the latest deployment scripts can deploy the runners normally, and the runners also behave normally.

**Logs**

**Notes**
Currently, a stable version of deployment script is provided to @leokondrashov

**Comment by ustiugov** [comment]
@lrq619 still an issue? otherwise please close
