### ISSUE TITLE
Tests not run for some PRs but required to pass

### ISSUE THREAD

**Issue by leokondrashov** [vhive-serverless/vHive#984]
**Describe the bug**
Github actions block the merge of the PRs with only changed markdown files. We require code quality and unit tests to pass, but we don't run them for PRs based on changed files.

**To Reproduce**
Make a PR that changes only markdown files.

**Expected behavior**
Allow the PR to be merged.

**Logs**
N/A

**Notes**
N/A

**Comment by leokondrashov** [comment]
@JooyoungPark73 Please take a look at #983, for example. We require unit tests to pass, but they are excluded from execution.

**Comment by JooyoungPark73** [comment]
There is a [reference doc](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks) regarding this issue. I'll take care of this issue, according to the doc.
